
env:
  - GH_USER=gheeci GH_REPO=ghee_test GH_ORG=ghee-org

language: ruby

notifications:
  slack:
    on_success: always
    on_failure: always

script: bundle exec rake spec

before_install:
  - gem install bundler -v 1.12
